export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_SINGLE_CHARACTERS = 'FETCH_SINGLE_CHARACTERS';
export const IS_FETCHING = 'IS_FETCHING';
export const SET_LOAD_STATE = 'SET_LOAD_STATE';
