export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_COMICS = 'FETCH_COMICS';
export const FETCH_SERIES = 'FETCH_SERIES';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_CREATORS = 'FETCH_CREATORS';

export const FETCH_SINGLE_CHARACTERS = 'FETCH_SINGLE_CHARACTERS';
export const FETCH_SINGLE_COMIC_BOOK = 'FETCH_SINGLE_COMIC_BOOK';
export const FETCH_SINGLE_SERIES = 'FETCH_SINGLE_SERIES';
export const FETCH_SINGLE_EVENT = 'FETCH_SINGLE_EVENT';
export const FETCH_SINGLE_CREATOR = 'FETCH_SINGLE_CREATOR';

export const CHARACTERS_FETCHING = 'CHARACTERS_FETCHING';
export const COMICS_FETCHING = 'COMICS_FETCHING';
export const SERIES_FETCHING = 'SERIES_FETCHING';
export const EVENTS_FETCHING = 'EVENTS_FETCHING';
export const CREATORS_FETCHING = 'CREATORS_FETCHING';

export const TOTAL_RESULT = 'TOTAL_RESULT';
export const SET_FILTERS = 'SET_FILTERS';
export const CHANGE_OFFSET = 'CHANGE_OFFSET';
